name: Test

on:
  push:
    paths:
      - 'CollaborativeCoding/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'CollaborativeCoding/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '2.0.5-0' # any version from https://github.com/mamba-org/micromamba-releases
        environment-file: environment.yml
        init-shell: bash
        cache-environment: true
        post-cleanup: 'all'
        generate-run-shell: false

    - name: Run tests
      run: |
        pytest
      shell: bash -el {0}
